/*! Generated by redux-scfld not for editing */
'use strict';


// Statuses
export const STATUS_PROCESS = 'STATUS_PROCESS';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';

// Generated Namespaces
export const NAMESPACE_GLOBAL = 'global';
export const NAMESPACE_OPTIONS = 'options';
export const NAMESPACE_RESOLVER = 'resolver';
export const NAMESPACE_TOTEMS = 'totems';

export const NAMESPACES = [
    NAMESPACE_GLOBAL,
    NAMESPACE_OPTIONS,
    NAMESPACE_RESOLVER,
    NAMESPACE_TOTEMS
];
// Generated Types
export const GLOBAL_BLOCK_INPUT = 'GLOBAL_BLOCK_INPUT';
export const OPTIONS_DISPLAY = 'OPTIONS_DISPLAY';
export const OPTIONS_SET = 'OPTIONS_SET';
export const RESOLVER_DONE = 'RESOLVER_DONE';
export const RESOLVER_SET_PROGRESS = 'RESOLVER_SET_PROGRESS';
export const RESOLVER_START = 'RESOLVER_START';
export const TOTEMS_FLIP_ONE = 'TOTEMS_FLIP_ONE';
export const TOTEMS_FLIP = 'TOTEMS_FLIP';
export const TOTEMS_REPLACE = 'TOTEMS_REPLACE';
export const TOTEMS_RESET = 'TOTEMS_RESET';
export const TOTEMS_SOLVE = 'TOTEMS_SOLVE';