/*! Generated by redux-scfld not for editing */
'use strict';

import global from './global';
import options from './options';
import resolver from './resolver';
import totems from './totems';

export default {
    global,
    options,
    resolver,
    totems
};
