/*! Generated by redux-scfld */
'use strict';

import {MODE_PLAY} from '../constants';

export default {
    mode: MODE_PLAY,
    width: 5,
    height: 5,
    maxPopulationSize: 500,
    maxGenerations: 100
};