/*! Generated by redux-scfld */
'use strict';


import {
    STATUS_PROCESS,
    STATUS_SUCCESS,
    STATUS_FAILURE
} from './../types';

export default function(state, action) {
    switch(action.status) {
        case STATUS_PROCESS:
            break;
        case STATUS_SUCCESS:
            return action.result;
        case STATUS_FAILURE:
            console.error(action.error);
            break;
    }
    return state;
}